


export const metadata = {
    title: '121doc en',
    description: 'Generated by create next app',
  };

  export async function generateStaticParams(){
    return [{lang: 'en'}, {lang: 'de'}];
  }
  
  export default function Root({ children, params }) {
    return (
      <html lang={params.lang}>
        <body>{children}</body>
      </html>
    );
  }
  